---
title: "Planned analysis"
subtitle: "Project ChaT-OS"
author:
  - name: "Jürgen Schneider"
    email: "ju.schneider@dipf.de"
    affiliation: "DIPF"
    correspondence: true
date: "`r Sys.Date()`" # inserts the date of compiling
editor: source
execute:
  eval: false
  echo: true
  warning: false
  message: false
  cache: false # true will prevent embed-resources
format: 
  html:
    theme: ceruleanc
    number-sections: true
    fontsize: 0.85em
    toc: true
    toc-location: left
    toc-depth: 3
    embed-resources: true # will make standalone html file
    code-fold: false
    code-tools: true
    code-link: true
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(lavaan)
library(tidyverse)
library(brms)
```

# Model

## Path model
```{r }
os_model <- "
  appraisal_challe ~ lamb1*resource_perso_eos + 
                     lamb2*resource_perso_lva + 
                     lamb3*resource_perso_exp + 
                     lamb4*resource_infra
  appraisal_threat ~ lamb5*resource_perso_eos + 
                     lamb6*resource_perso_lva + 
                     lamb7*resource_perso_exp + 
                     lamb8*resource_infra
 
  engagement ~ lamb9*appraisal_challe + 
               lamb10*appraisal_threat + 
               lamb11*resource_perso_eos + 
               lamb12*resource_perso_lva + 
               lamb13*resource_perso_exp + 
               lamb14*resource_infra

  appraisal_challe ~~ cov1*appraisal_challe
  appraisal_threat ~~ cov2*appraisal_threat
"


fit <- lavaan::sem(os_model, sim_data)
summary(fit, standardized = TRUE)
```


## Bayesian Model

```{r}

model_appaisal <- brms::bf(appraisal_challe ~ resource_perso_eos + 
                                        resource_perso_lva + 
                                        resource_perso_exp + 
                                        resource_infra)

model_threat <- brms::bf(appraisal_threat ~ resource_perso_eos + 
                                      resource_perso_lva + 
                                      resource_perso_exp + 
                                      resource_infra)

model_engagement <- brms::bf(engagement ~ appraisal_challe + 
                                    appraisal_threat + 
                                    resource_perso_eos + 
                                    resource_perso_lva + 
                                    resource_perso_exp + 
                                    resource_infra)

fit_brms <- brms::brm(model_appaisal +
                        model_threat + 
                        model_engagement +
                        set_rescor(FALSE),
                      data = sim_data,
                      cores = 4,
                      chains = 4,
                      iter = 4000)

```


\
\

# Computational environment

## Packages

```{r}
installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
```

## R Version

```{r}
R.Version()
```