---
title: "Extract sample from WoS"
subtitle: ""
author:
  - name: "Jürgen Schneider"
    email: "ju.schneider@dipf.de"
    affiliation: "DIPF"
    correspondence: true
date: "`r Sys.Date()`" # inserts the date of compiling
editor: source
execute:
  echo: true
  warning: false
  message: false
  cache: false # true will prevent embed-resources
format: 
  html:
    theme: ceruleanc
    number-sections: true
    fontsize: 0.85em
    toc: true
    toc-location: left
    toc-depth: 3
    embed-resources: true # will make standalone html file
    code-fold: true
    code-tools: true
    code-link: true
editor_options: 
  chunk_output_type: console
---

```{r packages}
#| echo: false
library(rio)
library(tidyverse)
library(here)
library(janitor)
```

## Import and wrangle

```{r import and wrangle}

# 1. Pfad zum Ordner (z.B. relativ im Projektordner)
data_folder <- here("data/WoS_exports/")

# 2. Alle .csv-Dateien im Ordner auflisten
file_list <- list.files(path = data_folder, pattern = "\\.xls$", full.names = TRUE)

# 3. Alle einlesen und zusammenfügen
dfs <- map(file_list, ~ {
  import(.x) %>%
    clean_names() %>%
    dplyr::select(any_of(c(
      "author_full_names", "article_title", "source_title",
      "author_keywords", "keywords_plus", "abstract",
      "email_addresses")))
  # df[columns_to_keep]
})

combined_data <- list_rbind(dfs)
rm(dfs)
```

## Search for keywords

### The keywords

```{r}
statistics <- c(
  "ANOVA",
  "t-test",
  "regression",
  "correlation",
  "correlate",
  "Cohen's",
  "p <",
  "p =",
  "p-value",
  "standard deviation",
  "confidence interval",
  "effect size",
  "odds ratio",
  "chi-square",
  "factor analysis",
  "path analysis",
  "latent variable",
  "structural equation model",
  " SEM ",
  "multivariate",
  "mediation analysis",
  "moderation analysis")

measurement <- c(
  "reliability",
  "Cronbach's",
  "internal consistency",
  "McDonald's",
  "measurement model",
  "item response",
  "Likert",
  "rating scale",
  "numeric scale")

software <- c(
  "SPSS",
  "RStudio",
  " R ",
  "Mplus",
  "Stata",
  "AMOS",
  "Matlab")

design <- c(
  "randomized controlled trial",
  "RCT",
  "pretest–posttest",
  "control group",
  "treatment group",
  "correlational")
```

### The search

```{r}
# 1. Vektoren zusammenführen
keywords <- c(statistics, measurement, software, design)

# 2. Regex bauen – ignoriert Groß-/Kleinschreibung
pattern <- str_c(keywords, collapse = "|")

# 3. `quant`-Spalte berechnen
combined_data <- combined_data %>%
  mutate(
    quant = if_else(
      replace_na(str_detect(article_title, regex(pattern, ignore_case = TRUE)), FALSE) |
      replace_na(str_detect(author_keywords, regex(pattern, ignore_case = TRUE)), FALSE) |
      replace_na(str_detect(keywords_plus, regex(pattern, ignore_case = TRUE)), FALSE) |
      replace_na(str_detect(abstract, regex(pattern, ignore_case = TRUE)), FALSE),
      1, 0
    )
  )
```

## Draw sample first batch

```{r}
sampled_data_b1 <- combined_data %>%
  dplyr::filter(quant == 1 &  # draw only from publications that indicate quantitative research
                !is.na(email_addresses) & 
                !is.na(article_title) & 
                !is.na(author_full_names)
                ) %>%
  slice_sample(n = 1550) %>%   # draw 10 times our needed N
  dplyr::mutate(
    firstname = paste(str_extract(author_full_names, "^[^,]+,\\s*([^;]+)",
                                  group = 1),
                      str_extract(author_full_names, "^[^,]+")),
    lastname = "see firstname",
    email = str_extract(email_addresses, "^[^;]+"), # get email of first author
    attribute_1 = article_title,
    sample_batch = 1) %>%
  dplyr::select(firstname, lastname, email, attribute_1, sample_batch)

rio::export(sampled_data_b1, here("data/sampled_data_batch1.csv"))
```


## Draw sample second batch

```{r}
sampled_data_b1 <- rio::import(here("data/sampled_data_batch1.csv"))

sampled_data_b2 <- combined_data %>%
  dplyr::filter(quant == 1 &  # draw only from publications that indicate quantitative research
                !is.na(email_addresses) & 
                !is.na(article_title) & 
                !is.na(author_full_names) &
                !(str_extract(email_addresses, "^[^;]+") %in% sampled_data_b1$email) # exclude emails that were in the first batch
                ) %>%
  slice_sample(n = 3100) %>%
  dplyr::mutate(
    firstname = paste(str_extract(author_full_names, "^[^,]+,\\s*([^;]+)",
                                  group = 1),
                      str_extract(author_full_names, "^[^,]+")),
    lastname = "see firstname",
    email = str_extract(email_addresses, "^[^;]+"), # get email of first author
    attribute_1 = article_title,
    sample_batch = 2) %>%
  dplyr::select(firstname, lastname, email, attribute_1, sample_batch)

rio::export(sampled_data_b2, here("data/sampled_data_batch2.csv"))
```

